### ISSUE TITLE
Cant connect to halite

### ISSUE THREAD

**Issue by Leopere** [bbinet/docker-salt-master#1]
Can there be a default config generated somewhere with this and also potentially some explanation as to how to pull up the halite panel in a webbrowser because http://<(IP-Address/Domainname)GoesHere:443/app> does not work.
It also seems that it is accepting auth attempts from a salt-minion but without access to halite its a bit silly.  

  docker run --name salt-master \
      -v /home/salt-master/config:/config \
      -v /home/salt-master/data:/data \
      -p 4505:4505 \
      -p 4506:4506 \
      -p 443:443 \
      bbinet/salt-master

**Comment by bbinet** [comment]
you need to:
- create a user via the before-exec script which will be run if you specify the `BEFORE_EXEC_SCRIPT` environment variable,
- configure halite in salt config file (see: http://docs.saltstack.com/en/latest/topics/tutorials/halite.html#configuring-halite-permissions and http://docs.saltstack.com/en/latest/topics/tutorials/halite.html#configuring-halite-settings)

I don't have time to improve the docs right now, but I'll be happy to review and merge pull requests.

**Comment by Leopere** [comment]
Would you be opposed to the concept of sharing an example that was sanitized?  That'd save so much work it'd practically be cheating.

**Comment by bbinet** [comment]
I'll try to find some time to share an example in the coming days.

**Comment by Leopere** [comment]
That would be amazing, I am fine with creating my own as well it would just be wise / awesome to throw in examples.
